dataset_name: pufanyi/flickr30k-jina-embeddings-v4
dataset_config: texts
data_files: null
split: train
revision: null
load_from_disk: null
id_column: id
embedding_column: embedding
metadata_columns:
  - caption
  - image_id
  - model_name
  - dataset_name
relevance_column: image_id
