dataset_name: pufanyi/inquire-siglip
dataset_config: queries
data_files: null
split: test
revision: null
load_from_disk: null
id_column: id
embedding_column: embedding
metadata_columns: []
relevance_column: image_id
