methods:
  - backend: faiss
    method: flat
    metric: cosine
  - backend: faiss
    method: ivf_flat
    metric: cosine
    nlist: 2048
    nprobe: 64
  - backend: faiss
    method: hnsw
    metric: cosine
    hnsw_m: 32
    ef_search: 128
top_k: 100
recall_at: [1, 5, 10, 50]
use_gpu: null
output_path: outputs/faiss_benchmark.csv
