methods:
  - backend: hnswlib
    method: hnswlib_default
    metric: cosine
    m: 32
    ef_construction: 200
    ef_search: 128
top_k: 100
recall_at: [1, 5, 10, 50]
use_gpu: false
output_path: outputs/hnswlib_benchmark.csv
