dataset_name: pufanyi/inquire-jina-embeddings
dataset_config: images
data_files: null
split: train
revision: null
load_from_disk: null
id_column: id
embedding_column: embedding
metadata_columns:
  - image_path
  - model_name
  - dataset_name
